### ISSUE TITLE
App breaking randomly - Android

### ISSUE THREAD

**Issue by kaushalvivek** [impulse/flutters#13]
The app is breaking randomly on an Android device. (PocoF1) Screenshot attached.
![image](https://user-images.githubusercontent.com/19169641/65179381-5942ee00-da78-11e9-9df8-4a7749495d87.png)

**Comment by impulse** [comment]
Is that the production or dev build? I know the Flame devs are aware of that issue (updated `pubspec` to latest version just in case it may fix it)

**Comment by kaushalvivek** [comment]
@impulse , this was a production build. The ```pubspec``` update seems to have fixed it.

**Comment by impulse** [comment]
Alright. This issue is Flame related, so if you keep running into this bug check out their repo for issues / solutions.
